name: Pipeline
on:
  workflow_run:
    branches:
      - main
  # or manually
  workflow_dispatch:

jobs:
    unit_test:
      name: Run tests and verify build
      runs-on: ubuntu-latest
      permissions:
          contents: read
          packages: write
      outputs:
        is_setup_pr: ${{ steps.pr_check.outputs.is_pr_for_setup }}
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - uses: 8BitJonny/gh-get-current-pr@3.0.0
            id: PR
          - run: |
              echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"
              echo "Your PR body is ${{ steps.PR.outputs.pr_body }}"

              if [[ "${{ steps.PR.outputs.pr_body }}" == "This is an automated pull request to add the Fly.io configuration files." ]]; then
                echo "is_pr_for_setup=true" >> $GITHUB_OUTPUT
              else
                echo "is_pr_for_setup=false" >> $GITHUB_OUTPUT
              fi
              echo "The value of is_pr_for_setup is:"
              cat $GITHUB_OUTPUT
            id: pr_check
            shell: bash

    print_output:
      name: Print output
      runs-on: ubuntu-latest
      needs: unit_test
      steps:
          - run: |
              echo "The value of is_setup_pr is ${{ needs.unit_test.outputs.is_setup_pr }}"
            shell: bash


